### ISSUE TITLE
Graph Readability

### ISSUE THREAD

**Issue by EigenFellow** [casact/covid_19_data#7]
Graph axis and labels are difficult to read due to the size and thickness of the fonts.

**Comment by ResearchActuary** [comment]
Are you referring to the Python or the R notebook?

**Comment by EigenFellow** [comment]
Beats me.  I just followed the link you gave me in the email to my work
account. I think it was Python.  Either that, or R with a vastly different
IDE that Rstudio.

**Comment by ResearchActuary** [comment]
Going to close this as it's something that users can adjust on their own. The display of Jupyter notebooks was purely for illustration.
